### Cadastrar despesa
POST http://localhost:3001
Content-Type: application/json

{
    "descricao" : "Conta de luz",
    "preco" : 120
}


### Listar Despesas
GET http://localhost:3001

### soma e media
GET http://localhost:3001/somaEMedia